name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        go_os: [linux, darwin, windows]
        go_arch: [amd64, arm64]
        include:
          - go_os: "linux"
            runner: ubuntu-latest
          - go_os: "darwin"
            runner: macos-latest
          - go_os: "windows"
            runner: windows-latest
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Build
        env:
          GOOS: ${{ matrix.go_os }}
          GOARCH: ${{ matrix.go_arch }}
        run: |
          go build -o build/nyoom-${{ matrix.go_os }}-${{ matrix.go_arch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nyoom-${{ matrix.go_os }}-${{ matrix.go_arch }}
          path: build/nyoom-${{ matrix.go_os }}-${{ matrix.go_arch }}
