name: Clippy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  clippy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          override: true

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Install clippy-sarif
        uses: cargo install clippy-sarif

      - name: Run clippy
        run: cargo clippy --all --all-targets --message-format=json | clippy-sarif > /tmp/clippy.sarif

      - name: Upload clippy results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: /tmp/clippy.sarif

      - name: Run rustfmt
        run: cargo fmt --all -- --check
